close all;
clc;
clear all;
a=imread('pic1.jpg');
b=imread('stego.jpg');
a1=a(:,:,1);
a2=a(:,:,2);
a3=a(:,:,3);
b1=b(:,:,1);
b2=b(:,:,2);
b3=b(:,:,3);
figure();
imhist(a1);
title('Original Histogram');
figure();
imhist(a2);
title('Original Histogram');
figure();
imhist(a3);
title('Original Histogram');
figure();
imhist(b1);
title('Stego-Image Histogram');
figure();
imhist(b2);
title('Stego-Image Histogram');
figure();
imhist(b3);
title('Stego-Image Histogram');
